# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: UK LLC Dataset Documentation
author: UK LLC Data Team
logo: docs/images/UKLLC_Lockup_Logo_Guidebook_Black+Coral_RGB.png
email: support@ukllc.ac.uk

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html


# Root folder for the book
#root: docs

execute:
  execute_notebooks: auto
  exclude_patterns:
    - '*freeze*'
    - '*scratchpad*'

# Exclude UK LLC profile pages
    - '*ukllc_key_facts/profile/ukllc_profile.ipynb'
    - '*ukllc_key_facts/sample/freezes/*'

# Exlude all LPS datasets and landing pages
    - '*lps_data/lps_profiles/*'
    - '*datasets/alspac/datasets/*'
    - '*datasets/bcs70/datasets/*'
    - '*datasets/bib/datasets/*'
    - '*datasets/elsa/datasets/*'
    - '*datasets/epicn/datasets/*'
    - '*datasets/exceed/datasets/*'
    - '*datasets/fenland/datasets/*'
    - '*datasets/genscot/datasets/*'
    - '*datasets/glad/datasets/*'
    - '*datasets/mcs/datasets/*'
    - '*datasets/ncds58/datasets/*'
    - '*datasets/nextstep/datasets/*'
    - '*datasets/nicola/datasets/*'
    - '*datasets/nihrbio_coping/datasets/*'
    - '*datasets/nshd46/datasets/*'
    - '*datasets/sabre/datasets/*'
    - '*datasets/teds/datasets/*'
    - '*datasets/trackc19/datasets/*'
    - '*datasets/twinsuk/datasets/*'
    - '*datasets/ukhls/datasets/*'

# Exclude PLACE datasets
    - '*AHAH*'
    - '*greenspace*'
    - '*air_pollution_o3*'
    - '*air_pollution_pm25_no2*'
    - '*noise_pollution*'
    - '*IMD*'
    - '*townsend*'

# exclude NHS England notebooks
    - 'linked_health_data/NHS_England/**/*.ipynb'

# exclude UKLLC 
    - 'ukllc_managed_data/datasets/NHSE_reference/*.ipynb'

bibtex_bibfiles:
   - _bibliography/references.bib

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/ukllc/jupyter-book  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  css_files:
    - custom.css
  extra_navbar: Visit our <a href="https://github.com/UKLLC/jupyter-book">GitHub Repository</a>
    <div>This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a></div>
  extra_footer: |
    CC BY-NC-SA The UK LLC Guidebook and materials are available publicly under <a href="https://github.com/UKLLC/licencing">open source licenses</a>
  favicon: "docs/images/favicon.ico"  # A path to a favicon image
  google_analytics_id: G-X3F2TFHCXV
  extra_js:
    - _static/open_details.js

parse:
  myst_enable_extensions:
    - html_image

# control footer copywrite
sphinx:
  config                    :  # key-value pairs to directly over-ride the Sphinx configuration
    html_show_copyright     : false
    html_sanitize_html        : false
    